name: test_app 
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  

  # 核心功能套件
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5
  #firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0


  # UI 與視覺化
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2

  # 原生功能與服務
  csv: ^6.0.0
  share_plus: ^7.2.2
  flutter_tts: ^4.0.2
  flutter_blue_plus: ^1.35.5
  video_player: ^2.8.6
  
  # --- 提醒功能必要的套件 ---
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  image_picker: ^1.2.1
  health: ^13.2.1
  permission_handler: ^12.0.1
  google_generative_ai: ^0.4.7
  
  # ML & Camera
  camera: ^0.11.0+1
  tflite_flutter: ^0.12.1
  image: ^4.1.7
  video_thumbnail: ^0.5.3
  ffmpeg_kit_flutter_new: ^4.1.0
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

  
flutter:
  uses-material-design: true
  assets:
    - image/icon/
    - image/page_icon/
    - assets/models/
    - assets/images/

flutter_launcher_icons:
  android: true 
  ios: true    
  image_path: "image/app_icon/icon.png"